# Generated by Django 3.2.4 on 2021-06-19 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('classid', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoutine',
            fields=[
                ('routineid', models.AutoField(primary_key=True, serialize=False)),
                ('ClassRoom', models.CharField(default='', max_length=100)),
                ('start', models.CharField(default='', max_length=100)),
                ('end', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(default='', max_length=100)),
                ('teacher', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=20)),
                ('location', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
